services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 10s ; python3 ./api.py"
    depends_on:
      - mysql
    ports:
      - '7007:7007'
    networks:
      - mysql-phpmyadmin

  mysql:
    build: ./mysql/
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: 'mysql'
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  db_data: